//import metadata, allows us to define page title and description
import type { Metadata } from "next";
//import global css file to allow styling
import "./globals.css";
//used for client side navigation between pages
import Link from "next/link";

//metadata object for the app, controls browser tab title and meta description
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//RootLayout is the main wrapper for every page, every page gets rendered in this layout
export default function RootLayout({
  //children = current page content
  children,
}: Readonly<{
  //children content must be react content
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body className="min-h-full flex flex-col">

        {/* setup shared layout and nav */}


        {/*navbar setup */}
        <nav className="bg-red-600 text-white px-4 py-3 flex gap-4 items-center">
          <h1 className="font-bold text-lg">PokeBrowser</h1>
          
          {/*contaier for nav links */}
          <div className="ml-auto flex gap-4">
              <Link href="/" className="hover:underline">Home</Link>
              <Link href="/pokemons" className="hover:underline ">Pokemons</Link>
          </div>

        </nav>
        {/* children content depends on current page */}
        <main>{children}</main>
      </body>
    </html>
  );
}
