import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        {/* setup shared layout and nav */}


        <nav className="bg-red-600 text-white px-4 py-3 flex gap-4 items-center">
          <h1 className="font-bold text-lg">PokeBrowser</h1>
          
          <div className="ml-auto flex gap-4">
              <Link href="/" className="hover:underline">Home</Link>
              <Link href="/pokemons" className="hover:underline ">Pokemons</Link>
          </div>

        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
